apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: xyz
spec:
  # Headless service - no ClusterIP assigned
  clusterIP: None
  ports:
  - name: redis-svc-port
    port: 6379
    targetPort: 6379
    protocol: TCP
  # No selector - we will manually define Endpoints

